server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8899
    gateway:
#      default-filters: #默认过滤器，对所有请求都生效
#        - AddRequestHeader=Truth,deng-study-spring-cloud
      routes: #网关配置
       - id: user-service #路由id,必须唯一
         filters: #过滤器
           - AddRequestHeader=Truth,deng-study-spring-cloud
       #uri: http://127.0.0.1:8081 #路由的目标地址，http就是固定地址
         uri: lb://userService #路由地址,lb负载均衡,userService服务名称
         predicates: #断言,判断是否符合路由规则的条件
           - Path=/user/** #路径匹配，user开头的请求才符合规则
           - Before=2032-02-12T14:22:22.995Z # 注意这里使用了Z表示UTC时间
       - id: order-service
         uri: lb://orderService
         predicates:
           - Path=/order/**
spring:
  cloud:
    gateway:
      globalcors: #全局的跨域处理
        #解决options请求被拦截的问题  跨域由浏览器向服务起发起一次访问，不开启的话浏览器无法访问服务器
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]': #拦截所有请求
            allowedOrigins: #允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
