server:
  port: 8076
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      server-addr: localhost:80 #nacos访问地址
#      discovery:
#        cluster-name: CQ #集群名称
#        namespace: 950952ca-8281-4b9b-92a0-087408b46e23 #命名空间
#  application:
#    name: orderService
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true #开启feign对httpclient的支持
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #每个路径最大的连接数
  client:
    config:
      #使用default就是全局配置，如果写服务名称就是针对某一个微服务的配置
#      userService:
      default:
        logger-level: full #日志规则



#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8065/eureka
# 负载均衡规则
#userService:
#  ribbon:
##    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RandomRule
#    NFLoadBalanceRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

#ribbon:
#  eager-load:
#    enabled: true #开启饥饿加载
#    clients:
#     - userService #指定对应的service服务进行饥饿加载
##     - orderService #指定对应的service服务进行饥饿加载
